<?php include './includes/head.php'; ?>
<?php include './includes/navbar.php'; ?>
<?php include './includes/hero.php'; ?>
<?php include './includes/about.php'; ?>
<?php include './includes/skills.php'; ?>
<?php include './includes/projectSection.php'; ?>
<?php include './includes/certificate.php'; ?>
<?php include './includes/contact.php'; ?>
<?php include './includes/footer.php'; ?>
